# Generated by Django 3.1.5 on 2021-05-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_name',
            field=models.TextField(default='Гость', max_length=30),
        ),
    ]
