# Generated by Django 3.1.5 on 2021-05-30 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210530_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='author_name',
        ),
    ]
