# Generated by Django 3.1.5 on 2021-05-30 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210530_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_name',
            new_name='user',
        ),
    ]
