# Generated by Django 3.1.5 on 2021-05-30 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
    ]
