# Generated by Django 3.1.5 on 2021-06-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20210530_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=5)),
                ('description', models.TextField()),
                ('img_title', models.CharField(max_length=30)),
            ],
        ),
    ]
