# Generated by Django 3.1.5 on 2021-06-04 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
