# Generated by Django 3.1.5 on 2021-06-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20210604_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='post-img.png', upload_to='pages/static/pages/img'),
        ),
    ]
