# Generated by Django 3.1.5 on 2021-06-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
