# Generated by Django 4.0.3 on 2022-07-01 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_historicalpost_historicalcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='historicalcomment',
            old_name='post_id',
            new_name='post',
        ),
    ]
