# Generated by Django 3.2 on 2022-07-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_rename_post_id_comment_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(default='Гость', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='user',
            field=models.CharField(default='Гость', max_length=50),
        ),
    ]
