# Generated by Django 3.2 on 2022-07-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_auto_20220701_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='anon_id',
            field=models.CharField(default='Аноним', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalcomment',
            name='anon_id',
            field=models.CharField(default='Аноним', max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(default='Аноним', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='user',
            field=models.CharField(default='Аноним', max_length=50),
        ),
    ]
