# Generated by Django 3.2 on 2022-07-01 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_auto_20220701_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='anon_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='historicalcomment',
            old_name='anon_id',
            new_name='user_id',
        ),
    ]
