# Generated by Django 3.2.3 on 2021-05-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('topic', models.CharField(max_length=30)),
                ('date', models.DateField()),
            ],
        ),
    ]
