# Generated by Django 3.2.3 on 2021-05-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursovaya', '0002_rename_topic_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
