# Generated by Django 3.2.3 on 2021-05-23 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kursovaya', '0004_auto_20210523_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
    ]
